global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8082']
        labels:
          application: 'e-commerce'